import argparse
import json
import os
import shlex
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import torch

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
NVIDIA_NCU_PYTHON_DIR = Path("/usr/local/cuda-12.9/nsight-compute-2025.2.0/extras/python")

if str(NVIDIA_NCU_PYTHON_DIR) not in sys.path:
    sys.path.insert(0, str(NVIDIA_NCU_PYTHON_DIR))

import ncu_report

DEFAULT_METRICS = (
    "lts__t_sector_op_read_hit_rate.pct",
    "lts__t_sector_op_write_hit_rate.pct",
)


def resolve_helper_script(name: str) -> Path:
    candidates = (
        REPO_ROOT / "scripts" / "cutracer_ffn_trace" / name,
        REPO_ROOT / "scripts" / "statistic" / name,
    )
    for path in candidates:
        if path.is_file():
            return path
    searched = "\n".join(f"- {path}" for path in candidates)
    raise FileNotFoundError(f"Could not find helper script {name}. Searched:\n{searched}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Profile replay_single_ffn_mlp.py with NVIDIA Nsight Compute and "
            "extract per-kernel L2 hit rates from the generated .ncu-rep report."
        ),
    )
    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument(
        "--capture",
        type=Path,
        help="Path to the FFN capture.pt file generated by the CUTracer workflow.",
    )
    source_group.add_argument(
        "--run-dir",
        type=Path,
        help="Run directory containing capture.pt, e.g. scripts/cutracer_ffn_trace/output/runs/layer_24_...",
    )
    parser.add_argument("--model-id", type=str, default=None, help="Optional model id override for replay.")
    parser.add_argument("--layer", type=int, default=None, help="Optional layer override for replay.")
    parser.add_argument(
        "--device-map",
        choices=["cuda", "auto"],
        default="auto",
        help="Replay placement strategy. Default matches the existing layer-24 workflow.",
    )
    parser.add_argument("--ncu", type=str, default="ncu", help="Path to the ncu executable.")
    parser.add_argument(
        "--python",
        type=str,
        default=sys.executable,
        help="Python executable used to launch replay_single_ffn_mlp.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory. Defaults to <run-dir>/ncu_l2/ or scripts/cutracer_ffn_trace/output/ncu/<timestamp>/",
    )
    parser.add_argument(
        "--metrics",
        type=str,
        default=",".join(DEFAULT_METRICS),
        help="Comma-separated Nsight Compute metrics to collect.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print commands and paths without launching Nsight Compute.",
    )
    return parser.parse_args()


def load_capture_payload(capture_path: Path) -> dict[str, Any]:
    if not capture_path.is_file():
        raise FileNotFoundError(f"Capture file does not exist: {capture_path}")
    return torch.load(capture_path, map_location="cpu", weights_only=True)


def resolve_capture_and_output(args: argparse.Namespace) -> tuple[Path, dict[str, Any], Path]:
    if args.run_dir is not None:
        run_dir = args.run_dir.resolve()
        capture_path = run_dir / "capture.pt"
    else:
        capture_path = args.capture.resolve()
        run_dir = capture_path.parent if capture_path.name == "capture.pt" else None

    payload = load_capture_payload(capture_path)

    if args.output_dir is not None:
        output_dir = args.output_dir.resolve()
    elif run_dir is not None:
        output_dir = run_dir / "ncu_l2"
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_dir = REPO_ROOT / "scripts" / "cutracer_ffn_trace" / "output" / "ncu" / timestamp

    output_dir.mkdir(parents=True, exist_ok=True)
    return capture_path, payload, output_dir


def resolve_ncu_executable(explicit_value: str) -> str:
    candidate = explicit_value.strip()
    explicit_path = Path(candidate).expanduser()
    if explicit_path.is_file():
        return str(explicit_path.resolve())

    resolved_from_path = shutil.which(candidate)
    if resolved_from_path:
        return str(Path(resolved_from_path).resolve())

    fallback_paths = (
        Path("/usr/local/cuda/bin/ncu"),
        Path("/usr/local/cuda-12.9/bin/ncu"),
        Path("/usr/local/cuda-12.8/bin/ncu"),
        Path("/usr/local/cuda-12.7/bin/ncu"),
    )
    for path in fallback_paths:
        if path.is_file():
            return str(path.resolve())

    searched = "\n".join(f"- {path}" for path in fallback_paths)
    raise FileNotFoundError(
        "Could not find the Nsight Compute CLI executable.\n"
        f"Requested value: {explicit_value}\n"
        "Searched PATH and these common locations:\n"
        f"{searched}\n"
        "Pass --ncu /absolute/path/to/ncu if it is installed elsewhere."
    )


def resolve_report_base(output_dir: Path, layer: int) -> Path:
    return output_dir / f"layer_{layer}_replay_l2"


def ncu_report_path(report_base: Path) -> Path:
    return Path(f"{report_base}.ncu-rep")


def resolve_ncu_tmpdir(output_dir: Path) -> Path:
    tmpdir = output_dir / ".ncu_tmp"
    tmpdir.mkdir(parents=True, exist_ok=True)
    return tmpdir


def command_to_shell(command: list[str]) -> str:
    return " ".join(shlex.quote(part) for part in command)


def build_ncu_environment(tmpdir: Path) -> dict[str, str]:
    env = os.environ.copy()
    tmpdir_str = str(tmpdir)
    env["TMPDIR"] = tmpdir_str
    env["TMP"] = tmpdir_str
    env["TEMP"] = tmpdir_str
    env["TEMPDIR"] = tmpdir_str
    return env


def run_subprocess(
    command: list[str],
    *,
    capture_output: bool = True,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        text=True,
        capture_output=capture_output,
        cwd=str(REPO_ROOT),
        env=env,
        check=False,
    )


def ensure_ncu_permissions(ncu_path: str, metric_name: str, env: dict[str, str]) -> None:
    probe = run_subprocess([ncu_path, "--query-metrics", "--metrics", metric_name], env=env)
    combined = f"{probe.stdout}\n{probe.stderr}"
    if "ERR_NVGPUCTRPERM" in combined:
        raise RuntimeError(
            "Nsight Compute cannot access GPU performance counters for the current user. "
            "The system returned ERR_NVGPUCTRPERM. Enable non-admin profiling "
            "(e.g. set NVreg_RestrictProfilingToAdminUsers=0 and reload the NVIDIA driver) "
            "or run the profiling command as root, then rerun this script."
        )
    if probe.returncode != 0:
        raise RuntimeError(
            "Failed to probe Nsight Compute metric availability.\n"
            f"Command: {' '.join(probe.args)}\n"
            f"stdout:\n{probe.stdout}\n"
            f"stderr:\n{probe.stderr}"
        )


def build_ncu_profile_command(
    *,
    args: argparse.Namespace,
    capture_path: Path,
    layer: int,
    report_base: Path,
) -> list[str]:
    replay_script = resolve_helper_script("replay_single_ffn_mlp.py")
    nvtx_range = f"ffn_replay_layer_{layer}/"
    command = [
        args.ncu,
        "--target-processes",
        "all",
        "--nvtx",
        "--nvtx-include",
        nvtx_range,
        "--metrics",
        args.metrics,
        "--cache-control",
        "none",
        "--clock-control",
        "none",
        "--export",
        str(report_base),
        "--force-overwrite",
        "--",
        args.python,
        str(replay_script),
        "--capture",
        str(capture_path),
        "--device-map",
        args.device_map,
    ]
    if args.model_id:
        command.extend(["--model-id", args.model_id])
    if args.layer is not None:
        command.extend(["--layer", str(args.layer)])
    return command


def build_ncu_csv_export_command(args: argparse.Namespace, report_path: Path) -> list[str]:
    return [
        args.ncu,
        "--import",
        str(report_path),
        "--csv",
        "--page",
        "raw",
        "--print-units",
        "base",
        "--print-fp",
    ]


def with_env_prefix(command: list[str], env: dict[str, str]) -> list[str]:
    prefixed = ["env"]
    for key in ("TMPDIR", "TMP", "TEMP", "TEMPDIR"):
        value = env.get(key)
        if value:
            prefixed.append(f"{key}={value}")
    prefixed.extend(command)
    return prefixed


def metric_value(action: Any, metric_name: str) -> float | None:
    metric = action.metric_by_name(metric_name)
    if metric is None or not metric.has_value():
        return None
    value = metric.value()
    if value is None:
        return None
    return float(value)


def parse_ncu_report(report_path: Path) -> list[dict[str, Any]]:
    context = ncu_report.load_report(report_path)
    kernels: list[dict[str, Any]] = []

    for range_index in range(context.num_ranges()):
        current_range = context.range_by_idx(range_index)
        for action_index in range(current_range.num_actions()):
            action = current_range.action_by_idx(action_index)
            if action.workload_type() != action.WorkloadType_KERNEL:
                continue

            kernel_name = action.name(action.NameBase_DEMANGLED)
            kernels.append(
                {
                    "range_index": range_index,
                    "action_index": action_index,
                    "kernel_name": kernel_name,
                    "l2_load_hit_rate_pct": metric_value(action, DEFAULT_METRICS[0]),
                    "l2_store_hit_rate_pct": metric_value(action, DEFAULT_METRICS[1]),
                }
            )

    if not kernels:
        raise RuntimeError(f"No kernel actions were found in Nsight Compute report: {report_path}")
    return kernels


def save_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def save_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")


def main() -> None:
    args = parse_args()
    args.ncu = resolve_ncu_executable(args.ncu)
    capture_path, payload, output_dir = resolve_capture_and_output(args)
    layer = args.layer if args.layer is not None else int(payload["layer"])
    ncu_tmpdir = resolve_ncu_tmpdir(output_dir)
    ncu_env = build_ncu_environment(ncu_tmpdir)
    report_base = resolve_report_base(output_dir, layer)
    report_path = ncu_report_path(report_base)
    csv_path = output_dir / f"{report_base.name}_raw.csv"
    summary_path = output_dir / f"{report_base.name}_summary.json"
    command_path = output_dir / "profile_replay_l2_command.sh"

    profile_command = build_ncu_profile_command(
        args=args,
        capture_path=capture_path,
        layer=layer,
        report_base=report_base,
    )
    csv_command = build_ncu_csv_export_command(args, report_path)

    command_text = (
        "# Nsight Compute profile command\n"
        f"{command_to_shell(with_env_prefix(profile_command, ncu_env))}\n\n"
        "# Export raw CSV from the generated report\n"
        f"{command_to_shell(with_env_prefix(csv_command, ncu_env))} > {csv_path}\n"
    )
    save_text(command_path, command_text)

    print("[ncu profile command]")
    print(command_to_shell(with_env_prefix(profile_command, ncu_env)))
    print()
    print("[ncu csv export command]")
    print(f"{command_to_shell(with_env_prefix(csv_command, ncu_env))} > {csv_path}")
    print()

    if args.dry_run:
        print(f"saved command script to: {command_path}")
        print("dry run only; no profiling was launched.")
        return

    ensure_ncu_permissions(args.ncu, DEFAULT_METRICS[0], ncu_env)

    profile_result = run_subprocess(profile_command, env=ncu_env)
    print("[ncu stdout]")
    print(profile_result.stdout)
    print("[ncu stderr]")
    print(profile_result.stderr)
    print()
    if profile_result.returncode != 0:
        raise RuntimeError(
            "Nsight Compute profiling failed.\n"
            f"Exit code: {profile_result.returncode}\n"
            f"Command: {command_to_shell(profile_command)}"
        )
    if not report_path.is_file():
        raise RuntimeError(f"Nsight Compute did not produce the expected report: {report_path}")

    csv_result = run_subprocess(csv_command, env=ncu_env)
    if csv_result.returncode != 0:
        raise RuntimeError(
            "Nsight Compute CSV export failed.\n"
            f"Exit code: {csv_result.returncode}\n"
            f"Command: {command_to_shell(csv_command)}\n"
            f"stdout:\n{csv_result.stdout}\n"
            f"stderr:\n{csv_result.stderr}"
        )
    save_text(csv_path, csv_result.stdout)

    kernels = parse_ncu_report(report_path)
    summary = {
        "capture": str(capture_path),
        "layer": layer,
        "model_id": args.model_id or payload.get("model_id"),
        "device_map": args.device_map,
        "nvtx_range": f"ffn_replay_layer_{layer}",
        "metrics": {
            "l2_load_hit_rate_pct": DEFAULT_METRICS[0],
            "l2_store_hit_rate_pct": DEFAULT_METRICS[1],
        },
        "report_path": str(report_path),
        "raw_csv_path": str(csv_path),
        "ncu_tmpdir": str(ncu_tmpdir),
        "profile_command": profile_command,
        "csv_export_command": csv_command,
        "kernels": kernels,
    }
    save_json(summary_path, summary)

    print("[done]")
    print(f"report: {report_path}")
    print(f"raw csv: {csv_path}")
    print(f"summary: {summary_path}")
    print("kernels:")
    for index, kernel in enumerate(kernels, start=1):
        print(
            f"  {index}. {kernel['kernel_name']} | "
            f"L2 load hit rate={kernel['l2_load_hit_rate_pct']} | "
            f"L2 store hit rate={kernel['l2_store_hit_rate_pct']}"
        )


if __name__ == "__main__":
    main()
